import test from 'node:test';
import assert from 'node:assert/strict';
import {businessDate,buildProject,taskState,toggleTask,toMarkdown,toCSV,validate} from '../../../docs/demo/engine.mjs';
const fixture={company:'Harbor & Pine',contact:'Morgan',email:'morgan@example.com',service:'website',goal:'Turn more website visits into qualified consultation requests.',kickoff:'2026-09-08',notes:'Keep the existing logo. The client will supply photography. Confirm who approves the final direction.'};
test('business dates cross weekends and leap days without timezone drift',()=>{assert.equal(businessDate('2026-09-05'),'2026-09-07');assert.equal(businessDate('2026-09-04',1),'2026-09-07');assert.equal(businessDate('2028-02-28',1),'2028-02-29');assert.throws(()=>businessDate('2026-02-30'));});
test('each service produces relevant work, contact details and seven dated tasks',()=>{for(const [service,role] of [['website','Web lead'],['media','Media lead'],['brand','Design lead']]){const p=buildProject({...fixture,service,company:'New Client'});assert.equal(p.tasks.length,7);assert.ok(p.tasks.some(t=>t.owner===role));assert.ok(p.welcome.body.includes('New Client'));assert.equal(p.tasks.at(-1).due,'2026-09-16');assert.ok(p.tasks.every(t=>![0,6].includes(new Date(t.due+'T12:00:00Z').getUTCDay())));}});
test('approval and both parallel prerequisites gate downstream completion',()=>{const p=buildProject(fixture);assert.throws(()=>toggleTask(p,'scope',true));p.approved=true;toggleTask(p,'scope',true);toggleTask(p,'kickoff',true);toggleTask(p,'brief',true);assert.throws(()=>toggleTask(p,'delivery',true));toggleTask(p,'assets',true);assert.equal(taskState(p.tasks.find(t=>t.id==='delivery'),p),'Ready');for(const id of ['delivery','review','handover'])toggleTask(p,id,true);assert.ok(p.tasks.every(t=>t.done));toggleTask(p,'assets',false);assert.deepEqual(p.tasks.filter(t=>t.done).map(t=>t.id),['scope','kickoff','brief']);});
test('invalid inputs fail without building a misleading project',()=>{assert.ok(validate({...fixture,email:'bad',goal:'short',service:'unknown'}).length===3);assert.throws(()=>buildProject({...fixture,company:' '}));});
test('exports retain the current approval state and escape CSV formulas',()=>{const p=buildProject({...fixture,company:'A & B, "Studio"'});assert.ok(toMarkdown(p).includes('A & B, "Studio"'));assert.ok(toMarkdown(p).includes('Draft for review'));p.approved=true;toggleTask(p,'scope',true);p.tasks[0].owner='=SUM(1,1)';const csv=toCSV(p);assert.ok(csv.includes('"\'=SUM(1,1)"'));assert.ok(csv.includes('"Done"'));assert.equal(csv.split('\r\n').length,8);});
